### ISSUE TITLE
ffmpg error

### ISSUE THREAD

**Issue by dalyafaraj** [theevann/streamlit-audiorecorder#10]
Can I define ffmpeg through yml or requirement.txt, and how, knowing that I am working on the web app , streamlit?
![Capture](https://github.com/theevann/streamlit-audiorecorder/assets/46635239/6fb4225d-86b9-4362-afd3-599fef0a5fe3)

**Comment by theevann** [comment]
Hello,
You need to install to ffmpeg on the server you are using.
If you are using streamline cloud, you should create a file named `packages.txt` in the root directory and add `ffmpeg` inside as shown here: [https://github.com/Franky1/Streamlit-ffmpeg-Test](https://github.com/Franky1/Streamlit-ffmpeg-Test)
