### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by sinclairfr** [theevann/streamlit-audiorecorder#12]
Hello,

I get :
```
Component Error
Cannot read properties of undefined (reading 'getUserMedia')
```
No recorder is shown, just a blank player.

Thanks

**Comment by sinclairfr** [comment]
![Screen Shot 2023-09-29 at 17 15 13](https://github.com/theevann/streamlit-audiorecorder/assets/118417/51bc9f9a-f500-4974-b84c-6c8d0c2b0931)

**Comment by theevann** [comment]
Please see https://github.com/theevann/streamlit-audiorecorder/issues/6

It is likely that you are serving your website as http, but 'getUserMedia' is available only when the website is served over https for security reasons.

If this is not your case, feel free to reopen.
