### ISSUE TITLE
Pause/resume

### ISSUE THREAD

**Issue by djk1983** [theevann/streamlit-audiorecorder#14]
Hi,

Thank you for your work on this. I have added the component into a streamlit application that records audio and then transcribes it via OpenAI's Whisper, then improves the grammar and formatting via GPT-3.5-turbo. It works very well. 

Would it be possible to add in a second button to pause/resume the recording?

Whilst I can dabble with python, I have no knowledge of JS/TS.

**Comment by theevann** [comment]
Hello !

Could you just clarify what the expected behavior is?
When you click pause, we should stop the recording but it should trigger no action on the streamlit side.
When you click stop, the overall recording should be sent to python for processing.
Is that what you had in mind ?

**Comment by djk1983** [comment]
Hello,

Yes, that is exactly what I had in mind. 

I am using my app to dictate file notes and emails. Being able to pause and think, then resume, would make it easier to record longer and more complex notes. 

Many thanks

**Comment by theevann** [comment]
I pushed an update on PyPI, you should be able to specify a pause text and see a pause button appear if you upgrade.
Let me know if it works fine for you.

**Comment by djk1983** [comment]
Thank you, much appreciated. I'm away this evening and will upgrade when I'm back tomorrow.

**Comment by djk1983** [comment]
Hi,

I have upgraded and the code functions as expected, albeit that the buttons do not render correctly. There is no text displayed (even when all three prompts are set when instantiating the widget in streamlit) and they are very small.

I really appreciate your work on this.

I am using MS Edge on Ubuntu. Also tried on Firefox, and Safari on iOS with the same rendering glitch.

**Comment by theevann** [comment]
I have not been able to reproduce the error you mention on my machine.
The streamlit cloud app also seems to work fine.
 Maybe try uninstalling and reinstalling it ?

**Comment by djk1983** [comment]
Thank you. I have it working properly in a local instance. Once packaged to a docker container the buttons fail to render correctly. I will continue to explore and see where I get to. Thank you for your help. Very much appreciated.
