### ISSUE TITLE
[Query] Is there a way to associate an animation/gif while recording.

### ISSUE THREAD

**Issue by e0lithic** [theevann/streamlit-audiorecorder#15]
Hi,

Currently the only indication of recording is the change of text. Is there a way we can perhaps also add animation (like `lottiefiles` or blinking red circle icon or microphone) which is more suggestive of the recording being in progress.

Great work by the way on having such a clean implementation.

**Comment by theevann** [comment]
Hey,
I am open to adding such a thing but I have no real idea what you have in mind in terms of UI.
Where would you put the animation ? Inside the button ?

Another possibility would be to trigger a streamlit rerun at each button press, to also return the recorder state along with the audio, and to let the user manage animations through streamlit. But I feel it is a bit overkill if only for this use case.

Can you elaborate a little ?

**Comment by e0lithic** [comment]
Hi,

For example, if we consider whatsapp for web, then pressing the microphone gives an interface as follows : 
![image](https://github.com/theevann/streamlit-audiorecorder/assets/11680315/5ba34c0e-da9b-482e-82c8-da73576f9278)

Although it's using the audio waveform directly instead of any animation but the overall effects seems to be to indicate of an ongoing recording in a more visual way.

**Comment by theevann** [comment]
Ok, thank you that is much clearer. 
One way I see would be to use smtg like
react-audio-recorder component: [Demo here](https://stackblitz.com/edit/react-ts-cc5l47?file=App.tsx),
or just to reuse some of their code to style this component.

It would be kind of a breaking api change compared to now, but it may be visually clearer and nicer, and I don’t see downsides.

**Comment by theevann** [comment]
Latest release v0.0.5 addresses this.
