### ISSUE TITLE
Only one recorder in two tabs after recording

### ISSUE THREAD

**Issue by Mifodix** [theevann/streamlit-audiorecorder#2]
Simple code for two recorders (each in different tab):
```
    tab1, tab2 = st.tabs(["TAB1", "TAB2",])
    with tab1:
        audio1 = audiorecorder("RECORDER 1", "Recording...", key="recorder1")
        if len(audio1) > 0:
            st.write(f"Audio1 len: {len(audio1)}")

    with tab2:
        audio2 = audiorecorder("RECORDER 2", "Recording...", key="recorder2")
        if len(audio2) > 0:
            st.write(f"Audio2 len: {len(audio2)}")
```

After using one recorder other recorder in different tab will be hidden.
Video: [streamlit-audiorecorder_tabs_bug.webm](https://user-images.githubusercontent.com/38187314/207908790-85886b7f-adce-4811-a821-3f3259d9f0dc.webm)

streamlit==1.15.2
streamlit-audiorecorder==0.0.2

**Comment by theevann** [comment]
I will have a look tomorrow.
I indeed never tested when using tabs.

**Comment by theevann** [comment]
It seems this is a streamlit bug unfortunately, probably linked with the issue linked above.
It may also be linked with https://github.com/streamlit/streamlit/issues/4996.

A workaround could be to do something like this where the user have to click the load button when switching tab:
```python
   tab1, tab2 = st.tabs(["TAB1", "TAB2",])
    with tab1:
        st.button("Load", key="tab1")
        audio1 = audiorecorder("RECORDER 1", "Recording...", key="recorder1")
        if len(audio1) > 0:
            st.write(f"Audio1 len: {len(audio1)}")

    with tab2:
        st.button("Load", key="tab2")
        audio2 = audiorecorder("RECORDER 2", "Recording...", key="recorder2")
        if len(audio2) > 0:
            st.write(f"Audio2 len: {len(audio2)}")
```

I don't really like this workaround, unfortunately this is a streamlit but and I don't think I can do much about it.
