### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by GXcells** [theevann/streamlit-audiorecorder#20]
I get a problem when hitting the stop button "FileNotFoundError: [WinError 2] The system cannot find the file specified"

This is when testing app in visual studio code (and I run visual studio code software first from my Command prompt after activating my conda env, because if I first run visual studio code even if I set the python interpreter to my conda env, it never recognize streamlit or conda).

I have all dependencies installed and I get the following error

`C:\Users\user\.conda\envs\streamlit\Lib\site-packages\pydub\utils.py:170: RuntimeWarning: Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work
  warn("Couldn't find ffmpeg or avconv - defaulting to ffmpeg, but may not work", RuntimeWarning)
C:\Users\user\.conda\envs\streamlit\Lib\site-packages\pydub\utils.py:198: RuntimeWarning: Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work
  warn("Couldn't find ffprobe or avprobe - defaulting to ffprobe, but may not work", RuntimeWarning)
2024-02-22 09:48:03.486 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\user\.conda\envs\streamlit\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\user\Documents\Python_projects\Streamlit_projects\Test1_Streamlit_App_v1\pages\2_🚀_page 2.py", line 8, in <module>
    audio = audiorecorder("Click to record", "Click to stop recording")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\streamlit\Lib\site-packages\audiorecorder\__init__.py", line 27, in audiorecorder
    audio_segment = AudioSegment.from_file(BytesIO(b64decode(base64_audio)))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\streamlit\Lib\site-packages\pydub\audio_segment.py", line 728, in from_file
    info = mediainfo_json(orig_file, read_ahead_limit=read_ahead_limit)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\streamlit\Lib\site-packages\pydub\utils.py", line 274, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.conda\envs\streamlit\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\user\.conda\envs\streamlit\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by theevann** [comment]
Hello,
It seems you did not install ffmpeg or it is not visible inside you environment.

From the readme:
> This package uses ffmpeg, so it should be installed for this audiorecorder to work properly.
>
> On ubuntu/debian: `sudo apt update && sudo apt install ffmpeg`
> On mac: `brew install ffmpeg`

Did you install it ?

**Comment by theevann** [comment]
I don’t think that’s the right way to install ffmpeg.
The library is not visible to other python program I guess.
I would recommend installing it by following this guide: https://phoenixnap.com/kb/ffmpeg-windows
