### ISSUE TITLE
how to change record Frame rate and  sampwidth?

### ISSUE THREAD

**Issue by lonngxiang** [theevann/streamlit-audiorecorder#21]

**Comment by theevann** [comment]
Hello!
Unfortunately, there are many inconsistencies across different browsers when setting the sample rate/width for audio recordings. Often, the sample rate is fixed and cannot be changed. Depending on the hardware and the browser, you can sometimes change it but it is very random and inconsistent. Therefore, I chose not to provide an interface to set the sample rate. The best in general is to post process the audio if you need a specific sample rate for further processing.
Sorry about that.
