### ISSUE TITLE
How to clear audiorecorder value after I process it, help!

### ISSUE THREAD

**Issue by HamaWhiteGG** [theevann/streamlit-audiorecorder#24]
When I use `audio = audiorecorder("", "")` to record audio and call `process_audio` to process it.
![image](https://github.com/theevann/streamlit-audiorecorder/assets/97529774/a44868a9-4b1c-4cd6-a972-4edd8c232cb3)

then switch the sidebar's radio value to 'low', `process_audio` is called again.
![image](https://github.com/theevann/streamlit-audiorecorder/assets/97529774/619e8d3f-dd78-4c4d-b777-ec3d33ae1fff)

I want the audio read when I click the sidebar to be empty, so `process_audio` is not called repeatedly.
like st.chat_input("Please enter a question").

```python
import streamlit as st
from audiorecorder import audiorecorder

st.title("Audio Recorder")
audio = audiorecorder("", "")

with st.sidebar:
    option = st.radio("Options", ["high", "medium", "low"])


def process_audio(audio_in):
    with st.chat_message("user"):
        st.write(f'Option: {option}')
        st.write("audio length:", len(audio_in))
        st.write("Process audio is finished")


if len(audio) > 0:
    # To play audio in frontend:
    st.audio(audio.export().read())

    # To save audio to a file, use pydub export method:
    audio.export("audio.wav", format="wav")

    process_audio(audio)

```

**Comment by theevann** [comment]
Hello !

It seems this is more of a streamlit question than an issue related to this component.
I think what you want to do is not very much in the spirit of how streamlit works.

The best way to avoid processing things repeatedly in streamlit is to use caching.
Please see [https://docs.streamlit.io/develop/api-reference/caching-and-state/st.cache_data](https://docs.streamlit.io/develop/api-reference/caching-and-state/st.cache_data)

For example, you could simply do:
```python
@st.cache_data
def process_audio(audio_in):
    with st.chat_message("user"):
        st.write(f'Option: {option}')
        st.write("audio length:", len(audio_in))
        st.write("Process audio is finished")
```

If this fail, you might need to make the audio_in input hashable with something like:

```python
from pydub import AudioSegment
import io
import hashlib

# Function to convert AudioSegment to a byte array
def audio_segment_to_bytes(audio_segment):
    buf = io.BytesIO()
    audio_segment.export(buf, format="wav")
    return buf.getvalue()

# Custom hash function for AudioSegment
def audio_segment_hash_func(audio_segment):
    byte_data = audio_segment_to_bytes(audio_segment)
    return hashlib.md5(byte_data).hexdigest()

# Cached function that takes an AudioSegment as input
@st.cache_data(hash_funcs={AudioSegment: audio_segment_hash_func})
def process_audio(audio_in):
    with st.chat_message("user"):
        st.write(f'Option: {option}')
        st.write("audio length:", len(audio_in))
        st.write("Process audio is finished")
```

If you really want to clear the audio when you click the radio, then you could something like:
```python

  def reset_audio():
    del st.session_state.audio

  option = st.radio("Options", ["high", "medium", "low"], on_change=reset_audio)
```

but again, I do not think this is the best way to go with this.

Hope this helps !
Good luck !

**Comment by theevann** [comment]
Otherwise:
If I understand well, what you want is that nothing happens when you click on the radio.
If that's the case, maybe wrapping it with an `@st.experimental_fragment` could work:

```python
@st.experimental_fragment
def define_option():
    with st.sidebar:
        option = st.radio("Options", ["high", "medium", "low"])

define_option()
```

and then you can access the option with `st.session_state.option`.

I didn't run any of the above code, so there may be errors...

**Comment by HamaWhiteGG** [comment]
Thank you very much for answering so quickly. I tested `st.cache_data(hash_funcs={AudioSegment: audio_segment_hash_func})` and it meets the requirements.

Yes, this is not the best way. But `st.chat_input` indeed works. When I enter the question and switch the radio on the sidebar, it does not repeat the call.

```python
import streamlit as st

st.title("chat_input example")

with st.sidebar:
    option = st.radio("Options", ["high", "medium", "low"])


def process_input(question_in):
    with st.chat_message("user"):
        st.write(f'Option: {option}')
        st.write("question_in:", question_in)
        st.write("Process audio is finished")


if question := st.chat_input("Please enter a question"):
    process_input(question)

```
When I input 'hello'：
![image](https://github.com/theevann/streamlit-audiorecorder/assets/97529774/086a1084-1e0d-4ef7-82bd-c1c21f16dac6)

when I click `low`, There is no output on the page because the `process_input` method is not being called.
![image](https://github.com/theevann/streamlit-audiorecorder/assets/97529774/490d57cc-b8d6-4b04-ae43-587f96ab08e7)

I actually wanted this effect.

**Comment by HamaWhiteGG** [comment]
> Otherwise: If I understand well, what you want is that nothing happens when you click on the radio. If that's the case, maybe wrapping it with an `@st.experimental_fragment` could work:
> 
> ```python
> @st.experimental_fragment
> def define_option():
>     with st.sidebar:
>         option = st.radio("Options", ["high", "medium", "low"])
> 
> define_option()
> ```
> 
> and then you can access the option with `st.session_state.option`.
> 
> I didn't run any of the above code, so there may be errors...



> Otherwise: If I understand well, what you want is that nothing happens when you click on the radio. If that's the case, maybe wrapping it with an `@st.experimental_fragment` could work:
> 
> ```python
> @st.experimental_fragment
> def define_option():
>     with st.sidebar:
>         option = st.radio("Options", ["high", "medium", "low"])
> 
> define_option()
> ```
> 
> and then you can access the option with `st.session_state.option`.
> 
> I didn't run any of the above code, so there may be errors...

Thanks，But I have multiple radio components, which makes my code more complex.

**Comment by HamaWhiteGG** [comment]
Now I use a Button to control whether to process speech. After the speech input is complete, the user needs to click the button to invoke the speech processing function. This causes a slight decrease in user experience and is not a good solution.

**Comment by theevann** [comment]
I see.

Maybe in your case the simplest is to delete the audio after processing....
```python
def process_audio(audio_in):
    with st.chat_message("user"):
        st.write(f'Option: {option}')
        st.write("audio length:", len(audio_in))
        st.write("Process audio is finished")
        del st.session_state.audio
```

Happy this could help !

**Comment by HamaWhiteGG** [comment]
> I see.
> 
> Maybe in your case the simplest is to delete the audio after processing....
> 
> ```python
> def process_audio(audio_in):
>     with st.chat_message("user"):
>         st.write(f'Option: {option}')
>         st.write("audio length:", len(audio_in))
>         st.write("Process audio is finished")
>         del st.session_state.audio
> ```
> 
> Happy this could help !

Thanks, but It doesn't work after I test it.

**Comment by HamaWhiteGG** [comment]
I add  `key="audio"` to audiorecorder. 
```python
import streamlit as st
from audiorecorder import audiorecorder

st.title("Audio Recorder")
audio = audiorecorder("", "", key="audio")

with st.sidebar:
    option = st.radio("Options", ["high", "medium", "low"])


def process_audio(audio_in):
    with st.chat_message("user"):
        st.write(f'Option: {option}')
        st.write("audio length:", len(audio_in))
        st.write("Process audio is finished")
        del st.session_state.audio


if len(audio) > 0:
    # To play audio in frontend:
    st.audio(audio.export().read())

    # To save audio to a file, use pydub export method:
    audio.export("audio.wav", format="wav")

    process_audio(audio)

```
