### ISSUE TITLE
How to custom style

### ISSUE THREAD

**Issue by tangtrongnghia** [theevann/streamlit-audiorecorder#26]
How to custom style ?

**Comment by OmarHory** [comment]
same question.

**Comment by theevann** [comment]
Latest release v0.0.6 allows for button styling: https://github.com/theevann/streamlit-audiorecorder/releases/tag/v0.0.6

The react-audio-recorder visualiser is a standalone npm component that cannot be customized here.
I could consider looking into this if there is demand, but it requires quite a bit of work.
