### ISSUE TITLE
put button into st.contrainer

### ISSUE THREAD

**Issue by goldengrape** [theevann/streamlit-audiorecorder#5]
Can I put it into a st.contrainer? 
How should I do this?

**Comment by B4PT0R** [comment]
> Can I put it into a st.contrainer? How should I do this?
Yes, just like every other streamlit component, using a "with" statement:
```python
c=st.container()
with c:
    audio = audiorecorder("Click to record", "Recording...")
```

**Comment by theevann** [comment]
Closing for now. If this does not solve your issue, feel free to reopen.
