### ISSUE TITLE
Getting component error in Network URL of streamlit

### ISSUE THREAD

**Issue by KushRJ** [theevann/streamlit-audiorecorder#6]
I get the following error when I use the audiorecorder with Network URL:

Component Error
Cannot read properties of undefined (reading 'getUserMedia')

How do I fix it?

**Comment by theevann** [comment]
Hello,
It seems it may be a browser issue, what browser are you using ?

**Comment by RizkiNoor16** [comment]
I have the same problem when building a Streamlit app using Docker. However, it runs normally when I use streamlit run .py command.

**Comment by theevann** [comment]
I will try to update the component to the latest streamlit version soon and that may fix this error.

**Comment by theevann** [comment]
I have updated the component, but I do not think it will have an impact on this.
Please try to give as much info as possible, currently I cannot reproduce this issue so I cannot fix it.

**Comment by hayk-corpusant** [comment]
More info:
<img width="757" alt="image" src="https://github.com/theevann/streamlit-audiorecorder/assets/123333651/6e8f6b84-5d6b-4a21-b5ea-dd47a754be7a">

**Comment by hayk-corpusant** [comment]
I believe it needs to be served over HTTPS to work: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by theevann** [comment]
Thank you @hayk-corpusant, that's probably it indeed !
Some more info about why [here](https://stackoverflow.com/questions/34197653/getusermedia-in-chrome-47-without-using-https)
I think I can close this then.
