### ISSUE TITLE
Auto-style the component according to current streamlit app's style.

### ISSUE THREAD

**Issue by B4PT0R** [theevann/streamlit-audiorecorder#7]
Hi,

Nice and useful widget ! 

Would it be possible to make the widget's css style to automatically match the current streamlit app's styling (colors) ?

Maybe [this](https://docs.streamlit.io/library/components/components-api) could be helpful ("Working with themes" section).

Would improve aesthetics.

Cheers !

**Comment by theevann** [comment]
The [new version](https://github.com/theevann/streamlit-audiorecorder/releases/tag/v0.0.3.post1) should solve this.
